/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_JNITest */

#ifndef _Included_utils_JNITest
#define _Included_utils_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_JNITest
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_utils_JNITest_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
